src/main/java/at/qe/sepm/skeleton/model/User.java
package at.qe.sepm.skeleton.model;

import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;
import org.springframework.data.domain.Persistable;

/**
 * Entity representing users.
 */
@Entity
public class User implements Persistable<String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(length = 100)
    private String username;

    @ManyToOne(optional = true)
    private User createUser;
	@Column(nullable = true)
    @Temporal(TemporalType.TIMESTAMP)
    private Date createDate;
    @ManyToOne(optional = true)
    private User updateUser;
    @Temporal(TemporalType.TIMESTAMP)
    private Date updateDate;

    private String password;
    
    private String firstName;
    private String lastName;
    private String email;
    private String phone;

    boolean enabled;

    @ElementCollection(targetClass = UserRole.class, fetch = FetchType.EAGER)
    @CollectionTable(name = "User_UserRole")
    @Enumerated(EnumType.STRING)
    private Set<UserRole> roles;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable( name = "user_gameroom", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "gameroom_id"))
    GameRoom gameRooms;
    
    @OneToMany(mappedBy = "author")
    @LazyCollection(LazyCollectionOption.FALSE)
    private List<Pool> pool;
        
	@OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE, CascadeType.REFRESH}, mappedBy = "player")
    @LazyCollection(LazyCollectionOption.FALSE)
    private List<AnswerStatistic> answerStatistics;
    
    
	 @OneToOne(mappedBy = "owner", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	 private UserProfile profile;

    public List<Pool> getPool() {
		return pool;
	}

	public void setPool(List<Pool> pool) {
		this.pool = pool;
	}

    
	public List<AnswerStatistic> getAnswerStatistics() {
		return answerStatistics;
	}

	public void setAnswerStatistics(List<AnswerStatistic> answerStatistics) {
		this.answerStatistics = answerStatistics;
	}

	public GameRoom getGameRooms() {
		return gameRooms;
	}

	public void setGameRooms(GameRoom gameRooms) {
		this.gameRooms = gameRooms;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public Set<UserRole> getRoles() {
        return roles;
    }
    
    public void setRoles(Set<UserRole> roles) {
        this.roles=roles;
    }

    public UserRole getRole() {
        return roles.iterator().next();
    }

    public void setRole(UserRole roles) {
        //this.roles.clear();
        this.roles.add(roles);
    }
    
    public User getCreateUser() {
        return createUser;
    }

    public void setCreateUser(User createUser) {
        this.createUser = createUser;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public User getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(User updateUser) {
        this.updateUser = updateUser;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

	public UserProfile getProfile() {
		return profile;
	}

	public void setProfile(UserProfile profile) {
		this.profile = profile;
	}

	@Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.username);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof User)) {
            return false;
        }
        final User other = (User) obj;
        if (!Objects.equals(this.username, other.username)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "at.qe.sepm.skeleton.model.User[ id=" + username + " ]";
    }

    @Override
    public String getId() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean isNew() {
        return (null == createDate);
    }

}

src/main/webapp/admin/createUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/main.xhtml">

	<ui:define name="content">
		<link type="text/css" rel="stylesheet"
			href="/resources/css_classes/nice.css" />


		<h:form id="userForm">


			<h1>
				<h:outputText value="CREATE USER" style="color:white;" />
			</h1>

			<p:messages showDetail="false" closable="true" showSummary="true">
				<p:autoUpdate />
			</p:messages>


			<h:panelGrid columns="2" style="margin: 0 auto;">
				<h:outputLabel value="Username: " class="schrift" />
				<p:inputText value="#{userDetailController.newUser.username}"
					class="inputtexter" required="true"
					requiredMessage="please enter a username" />

				<h:outputLabel value="Password: " class="schrift" />
				<p:inputText value="#{userDetailController.newUser.password}"
					class="inputtexter" required="true"
					requiredMessage="please enter a password" />

				<h:outputLabel value="Firstname: " class="schrift" />
				<p:inputText value="#{userDetailController.newUser.firstName}"
					class="inputtexter" required="true"
					requiredMessage="please enter your first name" />

				<h:outputLabel value="Lastname: " class="schrift" />
				<p:inputText value="#{userDetailController.newUser.lastName}"
					class="inputtexter" required="true"
					requiredMessage="please enter your las name" />

				<h:outputLabel value="E-Mail: " class="schrift" />
				<p:inputText value="#{userDetailController.newUser.email}"
					class="inputtexter" required="true"
					requiredMessage="please enter an email" />


				<h:outputLabel value="Role: " class="schrift" />
				<h:selectOneMenu value="#{userDetailController.chooseRole}"
					class="dropdownlist">
					<f:selectItem itemlabel="Player" itemValue="PLAYER" />
					<f:selectItem itemlabel="Teacher" itemValue="TEACHER" />
					<f:selectItem itemlabel="Admin" itemValue="ADMIN" />
				</h:selectOneMenu>



				<p:commandButton value="Save"
					action="#{userDetailController.doCreateUser()}"
					class="commandButton" onclick="PF('dlg1').show()" />


				<p:dialog header="User Saved" ind="dlg1" widgetVar="dlg1"
					height="100" width="500" style="margin: 0 auto;">
					<h:outputText
						value="The user was saved. To see all users go to Manage Users " />
				</p:dialog>


			</h:panelGrid>




		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/admin/manageuser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/main.xhtml">

	<head>
<link type="text/css" rel="stylesheet"
	href="/resources/css_classes/nice.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
	</head>

	<link type="text/css" rel="stylesheet"
		href="/resources/css_classes/nice.css" />


	<ui:define name="content">
		<h:form id="userForm">


			<h1>
				<h:outputText value="MANAGE USER" style="color:white;" />
			</h1>
			
			<p:dataTable id="usersTable" var="user"
				value="#{userListController.users}" styleClass="datatable"
				class="datatable">
				<p:column width="230" headerText="Username"
					filterBy="#{user.username}">
					<h:outputText value="#{user.username}" />
				</p:column>
				<p:column width="230" headerText="First Name"
					filterBy="#{user.firstName}">
					<h:outputText value="#{user.firstName}" />
				</p:column>
				<p:column filterBy="#{user.lastName}" width="230"
					headerText="Last Name">
					<h:outputText value="#{user.lastName}" />
				</p:column>
				<p:column headerText="Email">
					<h:outputText value="#{user.email}" />
				</p:column>
				<p:column filterBy="#{user.roles}" width="220" headerText="Roles"
					filterMatchMode="contains">
					<h:outputText value="#{user.roles}" />
				</p:column>
				<p:column style="width:140px;text-align: center">
					<p:commandButton update=":userForm:userEditDialog"
						oncomplete="PF('userEditDialog').show()" icon="ui-icon-note"
						title="Edit">
						<f:setPropertyActionListener value="#{user}"
							target="#{userDetailController.user}" />
					</p:commandButton>
					<p:commandButton action="#{userDetailController.doDeleteUser}"
						icon="ui-icon-trash" title="Delete" update=":userForm:usersTable">
						<f:setPropertyActionListener value="#{user}"
							target="#{userDetailController.user}" />
						<p:confirm header="Confirmation"
							message="Are you sure that you want to delete this user? You cannot undo this operation."
							icon="ui-icon-alert" />
					</p:commandButton>
				</p:column>
			</p:dataTable>

			<p:dialog header="Edit User" id="userEditDialog"
				widgetVar="userEditDialog" modal="true" showEffect="fade"
				hideEffect="fade" resizable="false">
				<p:outputPanel id="userData"
					rendered="#{not empty userDetailController.user}">
					<h:panelGrid columns="2">
						<p:outputLabel for="username" value="Username: " />
						<p:inputText id="username"
							value="#{userDetailController.user.username}" disabled="true" />
						<p:outputLabel for="password" value="Password: "/>
						<p:password id="password"
							value="#{userDetailController.user.password}" disabled="true"/>
					</h:panelGrid>
					<p:separator />
					<h:panelGrid columns="2">
						<p:outputLabel for="firstName" value="First Name: " />
						<p:inputText id="firstName"
							value="#{userDetailController.user.firstName}" />
						<p:outputLabel for="lastName" value="Last Name: " />
						<p:inputText id="lastName"
							value="#{userDetailController.user.lastName}" />
						<p:outputLabel for="email" value="E-Mail: " />
						<p:inputText id="email" value="#{userDetailController.user.email}" />
						<p:outputLabel for="roles" value="Role:" />
						<p:selectOneMenu id="roles"
							value="#{userDetailController.user.role}">
							<f:selectItem itemLabel="Player" itemValue="PLAYER" />
							<f:selectItem itemLabel="Teacher" itemValue="TEACHER" />
							<f:selectItem itemLabel="Admin" itemValue="ADMIN" />

						</p:selectOneMenu>

					</h:panelGrid>
					<p:separator />
					<h:panelGrid columns="3">
						<p:commandButton value="Save"
							action="#{userDetailController.doSaveUser()}"
							oncomplete="PF('userEditDialog').hide()"
							update=":userForm:usersTable" >
							</p:commandButton>
						<p:commandButton value="Reload"
							action="#{userDetailController.doReloadUser()}"
							update=":userForm:userData" />
						<p:commandButton value="Abort"
							onclick="PF('userEditDialog').hide()" />
					</h:panelGrid>
				</p:outputPanel>
			</p:dialog>

			<p:confirmDialog global="true" showEffect="fade" hideEffect="fade"
				width="300">
				<p:commandButton value="Yes" type="button"
					styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
				<p:commandButton value="No" type="button"
					styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
			</p:confirmDialog>

		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/admin/users.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form id="userForm">
            <p:dataTable id="usersTable" var="user" value="#{userListController.users}" style="margin: 0 auto;">
                <p:column headerText="Username">
                    <h:outputText value="#{user.username}"/>
                </p:column>
                <p:column headerText="First Name">
                    <h:outputText value="#{user.firstName}"/>
                </p:column>
                <p:column headerText="Last Name">
                    <h:outputText value="#{user.lastName}"/>
                </p:column>
                <p:column headerText="Roles">
                    <h:outputText value="#{user.roles}" />
                </p:column>
                <p:column headerText="Enabled">
                    <h:selectBooleanCheckbox value="#{user.enabled}" disabled="true"/>
                </p:column>
                <p:column style="width:100px;text-align: center">
                    <p:commandButton update=":userForm:userEditDialog" oncomplete="PF('userEditDialog').show()" icon="ui-icon-note" title="Edit">
                        <f:setPropertyActionListener value="#{user}" target="#{userDetailController.user}" />
                    </p:commandButton>
                    <p:commandButton action="#{userDetailController.doDeleteUser}" icon="ui-icon-trash" title="Delete" update=":userForm:usersTable">
                        <f:setPropertyActionListener value="#{user}" target="#{userDetailController.user}" />
                        <p:confirm header="Confirmation" message="Are you sure that you want to delete this user? You cannot undo this operation." icon="ui-icon-alert" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>

            <p:dialog header="Edit User" id="userEditDialog" widgetVar="userEditDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="userData" rendered="#{not empty userDetailController.user}">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="username" value="Username: " />
                        <p:inputText id="username" value="#{userDetailController.user.username}" disabled="true"/>
                        <p:outputLabel for="password" value="Password: " />
                        <p:password id="password" value="#{userDetailController.user.password}" disabled="true"/>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="2">
                        <p:outputLabel for="firstName" value="First Name: " />
                        <p:inputText id="firstName" value="#{userDetailController.user.firstName}"/>
                        <p:outputLabel for="firstName" value="Last Name: " />
                        <p:inputText id="lastName" value="#{userDetailController.user.lastName}"/>
                        <p:outputLabel for="email" value="E-Mail: " />
                        <p:inputText id="email" value="#{userDetailController.user.email}"/>
                        <p:outputLabel for="phone" value="Phone: " />
                        <p:inputMask id="phone" value="#{userDetailController.user.phone}" mask="+99? 999 9999999"/>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="2">
                        <p:outputLabel for="enabled" value="Enabled: " />
                        <p:selectBooleanCheckbox id="enabled" value="#{userDetailController.user.enabled}"/>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Save" action="#{userDetailController.doSaveUser()}" oncomplete="PF('userEditDialog').hide()" update=":userForm:usersTable"/>
                        <p:commandButton value="Reload" action="#{userDetailController.doReloadUser()}" update=":userForm:userData"/>
                        <p:commandButton value="Abort" onclick="PF('userEditDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>

            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" width="300">
                <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
            </p:confirmDialog>

        </h:form>
    </ui:define>
</ui:composition>