src/main/java/at/qe/sepm/skeleton/ui/controllers/PoolListController.java
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.Pool;
import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.services.PoolService;
import at.qe.sepm.skeleton.services.UserService;
import java.util.Collection;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;


@Component
@Scope("view")

public class PoolListController {


	@Autowired
	private PoolService poolService;
	@Autowired
	private UserService userService;

	/**
	 * Returns a list of all users.
	 *
	 * @return
	 */
	public Collection<Pool> getPools() {
		return poolService.getAllPools();
	}
	
	public List<Pool> getMyPools(){
		User user = userService.getAuthenticatedUser();
		return user.getPool();
	}


}

src/main/webapp/teacher/allpools.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/main.xhtml">

	<head>
<h:outputStylesheet library="css" name="/resources/css_classes/nice.css" />
	</head>

	<ui:define name="content">


		<link type="text/css" rel="stylesheet"
			href="/resources/css_classes/nice.css" />
		<h:form id="poolForm">

			<h1>
				<h:outputText value="ALL QUESTIONPOOLS" style="color:white;" />
			</h1>

			<h3>
				<h:outputText value="These are all available questionpools "
					style="color:white;" />
			</h3>



			<p:dataTable id="poolsTable" var="pool"
				value="#{poolListController.pools}" style="margin: 0 auto;">
				<p:column width="220" headerText="ID">
					<h:outputText value="#{pool.id}" />
				</p:column>
				<p:column width="220" headerText="Topic" filterBy="#{pool.topic}">
					<h:outputText value="#{pool.topic}" />
				</p:column>
				<p:column width="220" headerText="Difficulty"
					filterBy="#{pool.difficulty}">
					<h:outputText value="#{pool.difficulty}" />
				</p:column>
				<p:column>
					<p:commandButton update=":poolForm:questionDialog"
						oncomplete="PF('questionDialog').show()" icon="ui-icon-note"
						title="Edit">
						<f:setPropertyActionListener value="#{pool}"
							target="#{poolDetailController.pool}" />
					</p:commandButton>
				</p:column>
			</p:dataTable>

			<p:dialog id="questionDialog" header="Questions"
				widgetVar="questionDialog" modal="true" showEffect="fade"
				hideEffect="fade" class="hoila">
				<p:dataTable id="myPools" var="question"
					value="#{poolDetailController.pool.questions}"
					style="margin-bottom:40px" widgetVar="myPoolsTable">

					<p:column headerText="Question">
						<h:outputText value="#{question.question}" />
					</p:column>
					<p:column headerText="Answers">
						<p:dataList id="answers" value="#{question.answers}" var="answer"
							itemType="disc">
 							#{answer.getAnswer()}
 						</p:dataList>
					</p:column>
				</p:dataTable>



			</p:dialog>
		</h:form>


	</ui:define>
</ui:composition>

src/main/webapp/teacher/allstatistics.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/main.xhtml">


	<head>
<h:outputStylesheet library="css" name="/resources/css_classes/nice.css" />
	</head>
	<ui:define name="content">

		<h:outputStylesheet library="css"
			name="/resources/css_classes/nice.css" />

		<link type="text/css" rel="stylesheet"
			href="/resources/css_classes/nice.css" />

		<h:form id="answerStatisticForm">

			<h1>
				<h:outputText value="ALL STATISTICS" style="color:white;" />
			</h1>

			<h3>
				<h:outputText value="Statistics of other players"
					style="color:white;" />
			</h3>

			<p:dataTable id="usersTable" var="user"
				value="#{answerStatisticListController.users}">
				<p:column width="120" headerText="Username"
					filterBy="#{user.username}">
					<h:outputText value="#{user.username}" />
				</p:column>
				<p:column width="150" headerText="First Name"
					filterBy="#{user.firstName}">
					<h:outputText value="#{user.firstName}" />
				</p:column>
				<p:column width="150" headerText="Last Name"
					filterBy="#{user.lastName}">
					<h:outputText value="#{user.lastName}" />
				</p:column>
				<p:column style="width:100px;text-align: center">
					<p:commandButton
						update=":answerStatisticForm:answerStatisticDialog"
						oncomplete="PF('answerStatisticDialog').show()"
						icon="ui-icon-note" title="Show">
						<f:setPropertyActionListener value="#{user}"
							target="#{answerStatisticDetailController.user}" />
					</p:commandButton>
				</p:column>
			</p:dataTable>

			<p:dialog id="answerStatisticDialog" header="Statistic"
				widgetVar="answerStatisticDialog" modal="true" showEffect="fade"
				hideEffect="fade" resizable="true" height="100%" styleClass="hoila">

				<p:dataTable id="lastGamesPlayed" var="answerStatistic"
					value="#{answerStatisticDetailController.lastGamesPlayedAllStatistics()}"
					style="margin-bottom:40px" widgetVar="answerStatisticTable">


					<f:facet name="header">
            Last Games Played
        </f:facet>

					<p:column headerText="Percentage">
						<h:outputText value="#{answerStatistic.percentage}" />
					</p:column>
					<p:column headerText="Topic">
						<h:outputText value="#{answerStatistic.topic}" />
					</p:column>
					<p:column headerText="Right answers">
						<h:outputText value="#{answerStatistic.noSucceed}" />
					</p:column>
					<p:column headerText="Wrong answers">
						<h:outputText value="#{answerStatistic.noFailed}" />
					</p:column>
				</p:dataTable>



				<p:dataTable id="answerStatistic123" var="answerStatistic"
					value="#{answerStatisticDetailController.getAnswerStatisticsAllStatistics()}"
					style="margin-bottom:40px" emptyMessage="No Records found"
					widgetVar="answerStatisticTable">


					<f:facet name="header">
           				 Overall Statistics
        			</f:facet>
					<p:column headerText="Percentage" sortBy="#{answerStatistic[0]}">
						<h:outputText value="#{answerStatistic[0]}" />
					</p:column>
					<p:column filterBy="#{answerStatistic[1]}" headerText="Topic"
						filterMatchMode="contains">
						<h:outputText value="#{answerStatistic[1]}" />
					</p:column>
					<p:column headerText="Right answers">
						<h:outputText value="#{answerStatistic[2]}" />
					</p:column>
					<p:column headerText="Wrong answers">
						<h:outputText value="#{answerStatistic[3]}" />
					</p:column>
				</p:dataTable>

				<p:remoteCommand autoRun="true"
					oncomplete="PF('answerStatisticTable').filter();" />

			</p:dialog>



		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/teacher/createUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/main.xhtml">

	<ui:define name="content">
		<link type="text/css" rel="stylesheet"
			href="/resources/css_classes/nice.css" />

		<h:form id="userForm2">

			<h1>
				<h:outputText value="CREATE USER" style="color:white;" />
			</h1>

			<p:messages showDetail="false" closable="true">
				<p:autoUpdate />
			</p:messages>

			<h:panelGrid columns="2" style="margin: 0 auto;">
				<h:outputLabel for="username" value="Username: " class="schrift" />
				<p:inputText id="username"
					value="#{userDetailController.newUser.username}" required="true"
					requiredMessage="please enter a username" class="inputtexter" />

				<h:outputLabel for="password" value="Password: " class="schrift" />
				<p:inputText id="password"
					value="#{userDetailController.newUser.password}" required="true"
					requiredMessage="please enter a password" class="inputtexter" />

				<h:outputLabel for="firstname" value="Firstname: " class="schrift" />
				<p:inputText id="firstname"
					value="#{userDetailController.newUser.firstName}" required="true"
					requiredMessage="please enter your firstname" class="inputtexter" />

				<h:outputLabel for="lastname" value="Lastname: " class="schrift" />
				<p:inputText id="lastname"
					value="#{userDetailController.newUser.lastName}" required="true"
					class="inputtexter" requiredMessage="please enter your lastname" />

				<h:outputLabel for="email" value="E-Mail: " class="schrift" />
				<p:inputText id="email"
					value="#{userDetailController.newUser.email}" required="true"
					class="inputtexter" requiredMessage="please enter your e-mail" />


				<h:outputLabel for="role" value="Role: " class="schrift" />
				<h:selectOneMenu id="role"
					value="#{userDetailController.chooseRole}" class="dropdownlist">
					<f:selectItem itemlabel="Player" itemValue="PLAYER" />
					<f:selectItem itemlabel="Teacher" itemValue="TEACHER" />
					<f:selectItem itemlabel="Admin" itemValue="ADMIN" />
				</h:selectOneMenu>



				<p:commandButton name="h" value="Save"
					action="#{userDetailController.doCreateUser()}"
					class="commandButton" />

			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/teacher/createpool.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/main.xhtml">
	<ui:define name="content">
		<link type="text/css" rel="stylesheet"
			href="/resources/css_classes/nice.css" />




		<h:form id="form_lol">
			<h1>
				<h:outputText value="CREATE QUESTIONPOOL" style="color:white;" />
			</h1>

			<h3>
				<h:outputText
					value="Enter the topic, choose the difficulty and the amount of wrong answers "
					style="color:white;" />
			</h3>


			<p:messages showDetail="false" closable="true" showSummary="true">
				<p:autoUpdate />
			</p:messages>

			<h:panelGrid columns="2" style="margin: 0 auto;">
				<p:outputLabel value="Topic: " class="schrift" />
				<p:inputText id="topic" value="#{poolDetailController.pool.topic}"
					required="true" requiredMessage="please enter a Topic"
					class="inputtexter" />

				<p:outputLabel value="Difficulty: " class="schrift" />
				<h:selectOneMenu id="difficulty" value="#{poolDetailController.pool.difficulty}"
					class="dropdownlist">
					<f:selectItem itemlabel="Easy" itemValue="EASY" />
					<f:selectItem itemlabel="Hard" itemValue="HARD" />
				</h:selectOneMenu>

				<p:outputLabel value="Amount wrong answers: " class="schrift" />
				<h:selectOneMenu id="amount" value="#{poolDetailController.amount}"
					update=":form" class="dropdownlist" immediate="true">
					<f:selectItem itemlabel="3" itemValue="3" />
					<f:selectItem itemlabel="4" itemValue="4" />
					<f:selectItem itemlabel="5" itemValue="5" />
				</h:selectOneMenu>


				<p:commandButton  value="Add questions" update="@form"
					action="#{poolDetailController.doCreatePool()}"
					oncomplete="PF('dlg').show()" class="commandButton" />



				<p:dialog header="QuestionInput" widgetVar="dlg"
					showEffect="explode" hideEffect="puff" height="350" width="700"
					oncomplete="PF('dlg2').show();">



					<!--	<p:messages showDetail="false" closable="true" showSummary="true">
						<p:autoUpdate />
					</p:messages> -->


					<h:panelGrid columns="2" style="margin: 0 auto;">

						<p:outputLabel value="Question: " class="schrift" />
						<p:inputText id="q" value="#{poolDetailController.tester}"
							class="inputtexter" />

						<p:outputLabel value="Correct answer: " class="schrift" />
						<p:inputText id="a1" value="#{poolDetailController.test}"
							class="inputtexter" />


						<p:outputLabel value="Wrong answer 1: "
							rendered="#{poolDetailController.showDrei()}" class="schrift" />
						<p:inputText id="a2" value="#{poolDetailController.test}"
							rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

						<p:outputLabel value="Wrong answer 2: "
							rendered="#{poolDetailController.showDrei()}" class="schrift" />
						<p:inputText id="a3" value="#{poolDetailController.test}"
							rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

						<p:outputLabel value="Wrong answer 3: "
							rendered="#{poolDetailController.showDrei()}" class="schrift" />
						<p:inputText id="a4" value="#{poolDetailController.test}"
							rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

						<p:outputLabel value="Wrong answer 4: "
							rendered="#{poolDetailController.showVier()}" class="schrift" />
						<p:inputText id="a5" value="#{poolDetailController.test}"
							rendered="#{poolDetailController.showVier()}" class="inputtexter" />

						<p:outputLabel value="Wrong answer 5: "
							rendered="#{poolDetailController.showFunf()}" class="schrift" />
						<p:inputText id="a6" value="#{poolDetailController.test}"
							rendered="#{poolDetailController.showFunf()}" class="inputtexter" />

						<p:commandButton value="Save to Pool"
							action="#{poolDetailController.hoi()}"
							onclick="PF('dlg1').show();" class="commandButton" />

					</h:panelGrid>
				</p:dialog>



				<p:dialog header="Question Saved" widgetVar="dlg1" height="100"
					width="500" style="margin: 0 auto;">
					<h:outputText
						value="The Question was saved and added to the Questionpool. Type in a new one." />
				</p:dialog>

				<p:dialog header="Question Saved" widgetVar="dlg2" height="100"
					width="500" style="margin: 0 auto;">
					<h:outputText
						value="The Pool was saved. To see all pools go to All Questionpools " />
				</p:dialog>



			</h:panelGrid>

		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/teacher/mypools.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/main.xhtml">


	<head>
<h:outputStylesheet library="css" name="/resources/css_classes/nice.css" />
	</head>
	<ui:define name="content">

		<h:outputStylesheet library="css"
			name="/resources/css_classes/nice.css" />

		<link type="text/css" rel="stylesheet"
			href="/resources/css_classes/nice.css" />

		<h:form id="myPoolsForm">

			<h1>
				<h:outputText value="MY QUESTIONPOOLS" style="color:white;" />
			</h1>

			<h3>
				<h:outputText value="These are your questionpools "
					style="color:white;" />
			</h3>



			<p:dataTable id="myPoolsTable" var="pool"
				value="#{poolListController.getMyPools()}">
				<p:column width="120" headerText="Topic" filterBy="#{pool.topic}">
					<h:outputText value="#{pool.topic}" />
				</p:column>
				<p:column width="150" headerText="Difficulty"
					filterBy="#{pool.difficulty}">
					<h:outputText value="#{pool.difficulty}" />
				</p:column>
				<p:column style="width:100px;text-align: center">
					<p:commandButton update=":myPoolsForm2:myPoolsDialog"
						oncomplete="PF('myPoolsDialog').show()" icon="ui-icon-note"
						title="Show">
						<f:setPropertyActionListener value="#{pool}"
							target="#{poolDetailController.currentPool}" />
					</p:commandButton>
					<p:commandButton action="#{poolDetailController.doDeletePool}"
							icon="ui-icon-trash" title="Delete"
							update=":myPoolsForm:myPoolsTable">
							<f:setPropertyActionListener value="#{pool}"
								target="#{poolDetailController.currentPool}" />
							<p:confirm header="Confirmation"
								message="Are you sure that you want to delete this pool? You cannot undo this operation."
								icon="ui-icon-alert" />
						</p:commandButton>
					
				</p:column>
			</p:dataTable>
		</h:form>


		<h:form id="myPoolsForm2">
			<p:dialog id="myPoolsDialog" header="MyPools"
				widgetVar="myPoolsDialog" modal="true" showEffect="fade"
				hideEffect="fade" resizable="true" height="100%" class="hoila">

				<h:panelGrid columns="3" cellpadding="3">
					<p:commandButton value="Add questions" update=":myPoolsForm2:dlg" 
					action="#{poolDetailController.doAddQuestionsToPool()}" oncomplete="PF('dlg').show()"
					 class="commandButton"/>
					<p:outputLabel value="Amount wrong answers: " class="schrift" />
					<h:selectOneMenu value="#{poolDetailController.amount}"
						update=":form" class="dropdownlist">
						<f:selectItem itemlabel="3" itemValue="3" />
						<f:selectItem itemlabel="4" itemValue="4" />
						<f:selectItem itemlabel="5" itemValue="5" />
					</h:selectOneMenu>
				</h:panelGrid>

				<p:dataTable id="myPools" var="question"
					value="#{poolDetailController.currentPool.questions}"
					style="margin-bottom:40px" widgetVar="myPoolsTable">

					<p:column headerText="Question">
						<h:outputText value="#{question.question}" />
					</p:column>
					<p:column headerText="Answers">
						<p:dataList id="answers" value="#{question.answers}" var="answer"
							itemType="disc">
 							#{answer.getAnswer()}
 						</p:dataList>
					</p:column>
					<p:column>
						<p:commandButton action="#{poolDetailController.doSetAnswers()}"
							update=":myPoolsForm2:poolEditDialog"
							oncomplete="PF('poolEditDialog').show()" icon="ui-icon-note"
							title="Edit">
							<f:setPropertyActionListener value="#{question}"
								target="#{poolDetailController.questionDelete}" />
						</p:commandButton>
						<p:commandButton action="#{poolDetailController.doDeleteQuestion}"
							icon="ui-icon-trash" title="Delete"
							update=":myPoolsForm2:myPools">
							<f:setPropertyActionListener value="#{question}"
								target="#{poolDetailController.questionDelete}" />
							<p:confirm header="Confirmation"
								message="Are you sure that you want to delete this user? You cannot undo this operation."
								icon="ui-icon-alert" />
						</p:commandButton>
					</p:column>
				</p:dataTable>
			</p:dialog>

			<p:dialog header="Edit Question" id="poolEditDialog" modal="true"
				showEffect="explode" widgetVar="poolEditDialog" hideEffect="puff"
				resizable="false" height="350" width="700">



				<p:outputPanel id="questionData"
					rendered="#{not empty poolDetailController.questionDelete}">
					<h:panelGrid columns="2" style="margin: 0 auto;">
						<p:outputLabel for="question" value="Question: " />
						<p:inputText id="question"
							value="#{poolDetailController.questionDelete.question}" />

						<p:outputLabel value="Correct answer: " class="schrift" />
						<p:inputText value="#{poolDetailController.answers[0].answer}"
							class="inputtexter" />

						<p:outputLabel value="Wrong answer 1: "
							rendered="#{poolDetailController.showDrei()}" class="schrift" />
						<p:inputText value="#{poolDetailController.answers[1].answer}"
							rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

						<p:outputLabel value="Wrong answer 2: "
							rendered="#{poolDetailController.showDrei()}" class="schrift" />
						<p:inputText value="#{poolDetailController.answers[2].answer}"
							rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

						<p:outputLabel value="Wrong answer 3: "
							rendered="#{poolDetailController.showDrei()}" class="schrift" />
						<p:inputText value="#{poolDetailController.answers[3].answer}"
							rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

						<p:outputLabel value="Wrong answer 4: "
							rendered="#{poolDetailController.showVier()}" class="schrift" />
						<p:inputText value="#{poolDetailController.answers[4].answer}"
							rendered="#{poolDetailController.showVier()}" class="inputtexter" />

						<p:outputLabel value="Wrong answer 5: "
							rendered="#{poolDetailController.showFunf()}" class="schrift" />
						<p:inputText value="#{poolDetailController.answers[5].answer}"
							rendered="#{poolDetailController.showFunf()}" class="inputtexter" />

					</h:panelGrid>
					<h:panelGrid columns="2">
						<p:commandButton value="Save"
							action="#{poolDetailController.doSaveQuestion()}"
							oncomplete="PF('poolEditDialog').hide()"
							update=":myPoolsForm2:myPools" />
						<p:commandButton value="Abort"
							onclick="PF('poolEditDialog').hide()" />
					</h:panelGrid>
				</p:outputPanel>
			</p:dialog>

			<p:dialog header="QuestionInput" widgetVar="dlg" showEffect="explode"
				hideEffect="puff" height="350" width="700"
				oncomplete="PF('dlg2').show();"  id="dlg">
				<h:panelGrid columns="2" style="margin: 0 auto;">

					<p:outputLabel value="Question: " class="schrift" />
					<p:inputText value="#{poolDetailController.tester}"
						class="inputtexter" />

					<p:outputLabel value="Correct answer: " class="schrift" />
					<p:inputText value="#{poolDetailController.test}"
						class="inputtexter" />


					<p:outputLabel value="Wrong answer 1: "
						rendered="#{poolDetailController.showDrei()}" class="schrift" />
					<p:inputText value="#{poolDetailController.test}"
						rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

					<p:outputLabel value="Wrong answer 2: "
						rendered="#{poolDetailController.showDrei()}" class="schrift" />
					<p:inputText value="#{poolDetailController.test}"
						rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

					<p:outputLabel value="Wrong answer 3: "
						rendered="#{poolDetailController.showDrei()}" class="schrift" />
					<p:inputText value="#{poolDetailController.test}"
						rendered="#{poolDetailController.showDrei()}" class="inputtexter" />

					<p:outputLabel value="Wrong answer 4: "
						rendered="#{poolDetailController.showVier()}" class="schrift" />
					<p:inputText value="#{poolDetailController.test}"
						rendered="#{poolDetailController.showVier()}" class="inputtexter" />

					<p:outputLabel value="Wrong answer 5: "
						rendered="#{poolDetailController.showFunf()}" class="schrift" />
					<p:inputText value="#{poolDetailController.test}"
						rendered="#{poolDetailController.showFunf()}" class="inputtexter" />

					<p:commandButton value="Save to Pool"
						action="#{poolDetailController.hoi()}"
						onclick="PF('dlg1').show();" class="commandButton" 
						update=":myPoolsForm2:myPools"/>

				</h:panelGrid>
			</p:dialog>



			<p:dialog header="Question Saved" widgetVar="dlg1" height="100"
				width="500" style="margin: 0 auto;">
				<h:outputText
					value="The Question was saved and added to the Questionpool. Type in a new one." />
			</p:dialog>

			<p:dialog header="Question Saved" widgetVar="dlg2" height="100"
				width="500" style="margin: 0 auto;">
				<h:outputText
					value="The Pool was saved. To see all pools go to All Questionpools " />
			</p:dialog>

			<p:confirmDialog global="true" showEffect="fade" hideEffect="fade"
				width="300">
				<p:commandButton value="Yes" type="button"
					styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
				<p:commandButton value="No" type="button"
					styleClass="ui-confirmdialog-no" icon="ui-icon-close" />

			</p:confirmDialog>


		</h:form>
	</ui:define>
</ui:composition>