src/main/java/at/qe/sepm/skeleton/ui/beans/SessionInfoBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

/**
 * Session information bean to retrieve session-specific parameters.
 *
 * This class is part of the skeleton project provided for students of the
 * course "Softwaredevelopment and Project Management" offered by the University
 * of Innsbruck.
 */
@Component
@Scope("session")
public class SessionInfoBean {

    @Autowired
    private UserService userService;

    /**
     * Attribute to cache the current user.
     */
    private User currentUser;

    /**
     * Returns the currently logged on user, null if no user is authenticated
     * for this session.
     *
     * @return
     */
    public User getCurrentUser() {
        if (currentUser == null) {
            String currentUserName = getCurrentUserName();
            if (currentUserName.isEmpty()) {
                return null;
            }
            currentUser = userService.loadUser(currentUserName);
        }
        return currentUser;
    }

    /**
     * Returns the username of the user for this session, empty string if no
     * user has been authenticated for this session.
     *
     * @return
     */
    public String getCurrentUserName() {
        if (!isLoggedIn()) {
            return "";
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String name = auth.getName(); //get logged in username
        return name;
    }

    /**
     * Returns the roles of the user for this session as space-separated list,
     * empty string if no user has been authenticated for this session-
     *
     * @return
     */
    public String getCurrentUserRoles() {
        if (!isLoggedIn()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority role : auth.getAuthorities()) {
            sb.append(role.getAuthority());
            sb.append(' ');
        }
        return sb.toString().trim();
    }

    /**
     * Checks if a user is authenticated for this session.
     *
     * @return true if a non-anonymous user has been authenticated, false
     * otherwise
     */
    public boolean isLoggedIn() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null) {
            return auth.isAuthenticated() && !auth.getName().equals("anonymousUser");
        } else {
            return false;
        }
    }

    /**
     * Checks if the user for this session has the given role (c.f.
     * {@link UserRole}).
     *
     * @param role the role to check for as string
     * @return true if a user is authenticated and the current user has the
     * given role, false otherwise
     */
    public boolean hasRole(String role) {
        if (role == null || role.isEmpty() || !isLoggedIn()) {
            return false;
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority ga : auth.getAuthorities()) {
            if (role.equals(ga.getAuthority())) {
                return true;
            }
        }
        return false;
    }

    /**
     * Checks if logged in User is not a Player
     * @return true if user is logged in and not a player.
     */
    public boolean isntPlayer() {
    	return isLoggedIn() && !hasRole("PLAYER");
    }


}

src/main/webapp/WEB-INF/includes/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <body>
        <ui:composition>

            <div style="float: right;">
                <ui:fragment rendered="#{sessionInfoBean.loggedIn}">
                    Logged in as #{sessionInfoBean.currentUserName} [#{sessionInfoBean.currentUserRoles}]
                </ui:fragment>
                <ui:fragment rendered="#{!sessionInfoBean.loggedIn}">
                    Not logged in
                </ui:fragment>
            </div>

        </ui:composition>
    </body>
</html>

src/main/webapp/WEB-INF/includes/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<head>
<link type="text/css" rel="stylesheet"
	href="/resources/css_classes/nice.css" />

<link rel="stylesheet" href="/resources/css_classes/nice.css" />

</head>

<body>
	<ui:composition>
		<h:form>


			<link type="text/css" rel="stylesheet"
				href="/resources/css_classes/nice.css" />



			<!--  <p:menubar class="backgroundcolor">
				<p:menuitem value="Login" url="/login.xhtml"
					rendered="#{!sessionInfoBean.loggedIn}" />
				<p:menuitem value="Menu" oncomplete="PF('sidebar1').show()" />
			</p:menubar>-->
			<img src="/resources/css_classes/logoGruppeV.png" height="60"
				style="margin: 0 auto;" href="/user/creategame.xhtml" />
			<p:separator />

			<h:panelGrid columns="1">
				<img src="/resources/css_classes/menu.png" height="30" size="30"
					align="left" onclick="PF('sidebar1').show()" />
			</h:panelGrid>

			<!-- <p:commandButton value="Menu"
				oncomplete="PF('sidebar1').show()" style="align: left" /> -->

			<p:sidebar widgetVar="sidebar1" height="100%" style="margin: 0;">

				<p:menu toggleable="true" class="sidebarmenu" width="6080" style="margin: 0;">
					<p:submenu label="Play"
						rendered="#{sessionInfoBean.hasRole('PLAYER')}" class="menuer" style="color: black;">
						<p:menuitem value="Create game" url="/user/creategame.xhtml"
							class="menuitem" />
						<p:menuitem value="Join game" url="/user/joingame.xhtml"
							class="menuitem" />
					</p:submenu>
					<p:submenu label="Profile"
						rendered="#{sessionInfoBean.hasRole('PLAYER')}" class="menuer" style="color: black;"     	>
						<p:menuitem value="My profile" url="/user/myprofile.xhtml"
							class="menuitem" />
						<p:menuitem value="All profiles!" url="/user/allprofiles.xhtml"
							class="menuitem" />
						<p:menuitem value="Edit my profil" url="/user/editmyprofile.xhtml"
							class="menuitem" />
					</p:submenu>
					<p:submenu label="Statistics"
						rendered="#{sessionInfoBean.hasRole('PLAYER')}" class="menuer">
						<p:menuitem value="My statistics" url="/user/mystatistics.xhtml"
							class="menuitem" />
					</p:submenu>

					<p:submenu label="Play"
						rendered="#{sessionInfoBean.hasRole('TEACHER')}" class="menuer"> 
						<p:menuitem value="Create game" url="/user/creategame.xhtml"
							class="menuitem" />
						<p:menuitem value="Join game" url="/user/joingame.xhtml"
							class="menuitem" />
					</p:submenu>
					<p:submenu label="Profile"
						rendered="#{sessionInfoBean.hasRole('TEACHER')}" class="menuer">
						<p:menuitem value="My profile" url="/user/myprofile.xhtml"
							class="menuitem" />
						<p:menuitem value="All profiles" url="/user/allprofiles.xhtml"
							class="menuitem" />
							<p:menuitem value="Edit my profil" url="/user/editmyprofile.xhtml"
							class="menuitem" />
					</p:submenu>
					<p:submenu label="Statistics"
						rendered="#{sessionInfoBean.hasRole('TEACHER')}" class="menuer">
						<p:menuitem value="My statistics" url="/user/mystatistics.xhtml"
							class="menuitem" />
						<p:menuitem value="All statistics" url="/teacher/allstatistics.xhtml"
							class="menuitem" />
					</p:submenu>
					<p:submenu label="Questions"
						rendered="#{sessionInfoBean.hasRole('TEACHER')}" class="menuer">
						<p:menuitem value="Create Questionpool"
							url="/teacher/createpool.xhtml" class="menuitem" />
							<p:menuitem value="My Questionpools" url="/teacher/mypools.xhtml"
 						class="menuitem" />		
						<p:menuitem value="All Questionpools"
							url="/teacher/allpools.xhtml" class="menuitem" />
					</p:submenu>
					<p:submenu label="Users"
						rendered="#{sessionInfoBean.hasRole('TEACHER')}" class="menuer">
						<p:menuitem value="Create User" url="/teacher/createUser.xhtml"
							class="menuitem" />
					</p:submenu>

					<p:submenu label="Play"
						rendered="#{sessionInfoBean.hasRole('ADMIN')}" class="menuer">
						<p:menuitem value="Create game" url="/user/creategame.xhtml"
							class="menuitem" />
						<p:menuitem value="Join game" url="/user/joingame.xhtml"
							class="menuitem" />
					</p:submenu>
					<p:submenu label="Profile"
						rendered="#{sessionInfoBean.hasRole('ADMIN')}" class="menuer">
						<p:menuitem value="My profile!!" url="/user/myprofile.xhtml"
							class="menuitem" />
						<p:menuitem value="All profiles" url="/user/allprofiles.xhtml"
							class="menuitem" />
							<p:menuitem value="Edit my profil" url="/user/editmyprofile.xhtml"
							class="menuitem" />
					</p:submenu>
					<p:submenu label="Statistics"
						rendered="#{sessionInfoBean.hasRole('ADMIN')}" class="menuer">
						<p:menuitem value="My statistics" url="/user/mystatistics.xhtml"
							class="menuitem" />
						<p:menuitem value="All statistics" url="/teacher/allstatistics.xhtml"
							class="menuitem" />
					</p:submenu>
					<p:submenu label="Questions"
						rendered="#{sessionInfoBean.hasRole('ADMIN')}" class="menuer">
						<p:menuitem value="Create Questionpool"
							url="/teacher/createpool.xhtml" class="menuitem" />
							<p:menuitem value="My Questionpools" url="/teacher/mypools.xhtml" class="menuitem" />
						<p:menuitem value="All Questionpools"
							url="/teacher/allpools.xhtml" class="menuitem" />
					</p:submenu>
					<p:submenu label="Users"
						rendered="#{sessionInfoBean.hasRole('ADMIN')}" class="menuer">
						<p:menuitem value="Create User" url="/teacher/createUser.xhtml"
							class="menuitem" />
						
						<p:menuitem value="Manage User" url="/admin/manageuser.xhtml"
							class="menuitem" />
					</p:submenu>

					<p:menuitem value="Login" url="/login.xhtml"
						rendered="#{!sessionInfoBean.loggedIn}" class="menuitem" />
					<p:menuitem value="Logout" url="/logout"
						rendered="#{sessionInfoBean.loggedIn}" class="menuitem" />



				</p:menu>
			</p:sidebar>
		</h:form>
	</ui:composition>
</body>
</html>